# Site Details
site_name: Kapowarr Docs
site_description: The official guide for Kapowarr 
site_author: MrCas
#edit_uri: https://github.com/??
repo_url: https://github.com/Casvt/Kapowarr
repo_name: Casvt/Kapowarr

# Site appearance (logos, colours, icons)
theme:
  name: material
  language: en
  code_wrap: true
  features:
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
  #favicon: assets/logo/favicon.ico
  #logo: assets/logo/kapowarr-logo.png?
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extra CSS
extra_css:
  - assets/stylesheets/extra.css

# Markdown extensions
markdown_extensions:
  - abbr
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      guess_lang: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 5

# mkdocs function extensions
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: false

# Navigation Layout
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
